const STATUS_ACTIVE = 1
const STATUS_INACTIVE = 0
const TOKEN_KEY = "5xVpMrXK6g"
const AWS_ACCESS_KEY_ID = "AKIA5NZ245NVEMAI5UHA"
const AWS_SECRET_ACCESS_KEY = "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"

module.exports = {
    STATUS_ACTIVE, 
    STATUS_INACTIVE, 
    TOKEN_KEY,
    AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY
}