const STATUS_ACTIVE = 1
const STATUS_INACTIVE = 0
const TOKEN_KEY = "5xVpMrXK6g"
const AWS_ACCESS_KEY_ID = "AKIA5NZ245NVGBJRAJTG"
const AWS_SECRET_ACCESS_KEY = "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"

module.exports = {
    STATUS_ACTIVE, 
    STATUS_INACTIVE, 
    TOKEN_KEY,
    AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY
}